### ISSUE TITLE
Did anyone run the code successfully?

### ISSUE THREAD

**Issue by ycjing** [OlavHN/fast-neural-style#4]
Hi. Thanks for the code. However, when I run the code with python3.5 and tensorflow0.10.0, it always reported "Attempting to use uninitialized value input_producer/limit_epochs/epochs". I have no idea how to fix it after many attempts. Maybe it's due to my tensorflow version. Does anyone has any idea? Or someone who run the code successfully can share your tensorflow version and other configuration information? 
Thank you very much!

**Comment by OlavHN** [comment]
I believe this is due to the model originally being trained without a variable for keeping track of the epoch, but then loaded into a graph with such a variable.

Sorry for not updating this stuff.

I have a set of fixes for these things, but fixing the main issue with spotty images (see other issue) took more time than I had at the time. I'll get around to doing a proper update "any day now".

As for fixing the error you describe I believe you can run tf.initialize_all_variables() before loading the pretrained model, or train a new model yourself. https://github.com/bazarevsky/fast-neural-style - I haven't tested it, but this fork seems to have the necessary fix.

**Comment by ycjing** [comment]
@OlavHN Thanks a lot!
